# Site settings

title: Beans means coffee

description: "We drink a lot of coffee. This is what we think of the ones we try."
keywords: "coffee, espresso, latte, beans, taste test, cafe, drink"

baseurl: "" # e.g. /blog
url: "http://coffee.johnpe.art" # e.g. http://example.com
author: John Peart and David Greaves
logo: "/site/beans-means-coffee.png"

asset-path: "/assets"
image-path: "/images"
image-2x-path: "/images/@2x"
post-images-path: "/featured"
css-path: "/styles"
js-path: "/scripts"

# Social settings
facebook-app-id: "1053585037989505" # For Facebook OpenGraph integration
facebook-profile-id: "100003820028435" # For Facebook OpenGraph integration
facebook-slug: "john.robert.peart" # Automatically pre-pends http://facebook.com/
twitter-username: "johnpeart" # Twitter handle i.e. joebloggs
linkedin-username:  "jrpeart"
flickr-username:  "johnpeart"
instagram-username:  "johnpeart"
github-username:  "johnpeart"
google-site-verification: "DaqGCZ6cZIqm7q_nVSnOzjJmFFjbRfW2X7FDzpQDQZk" # GSV code; proves domain ownership

logo: "/site/logo.png"
social-media: "/site/social-media.png"
touch: "/site/touch.png"
pinned: "/site/pinned.svg"
pinned-colour: "#1d1d1d"

#Analytics
disable-analytics: false # Switch to "false" to start GA logging
google-analytics: "UA-27553664-5" # GA ID code

# Plugins and build settings

permalink: pretty
markdown: kramdown
future: false
sass:
    sass_dir: _sass
    sourcemap: true

gems:
- jekyll-sitemap
- jekyll-feed
- jekyll-redirect-from