# Site settings

title: Beans means coffee

description: "We drink a lot of coffee. This is what we think of the ones we try."
keywords: "coffee, espresso, latte, beans, taste test, cafe, drink"

baseurl: "" # e.g. /blog
url: "http://coffee.johnpeart.org" # e.g. http://example.com
author: John Peart and David Greaves
logo: "/beans-means-coffee.png"

asset-path: "/assets"
image-path: "/images"
image-2x-path: "/images/@2x"

# Social settings
facebook-id: "" # For Facebook OpenGraph integration
facebook-slug: "" # Automatically pre-pends http://facebook.com/
twitter-username: "" # Twitter handle i.e. joebloggs
github-username:  ""
google-site-verification: "GMEFdAl3i-jN_Jkdb_jrS-LWZPUEQ7Bx4fPcyQ7YSCU" # GSV code; proves domain ownership

#Analytics
disable-analytics: false # Switch to "false" to start GA logging
google-analytics: "UA-27553664-5" # GA ID code

# Plugins and build settings

permalink: /:title.html
markdown: kramdown
future: false
sass:
    sass_dir: _sass
    sourcemap: true

gems:
- jekyll-sitemap
- jekyll-feed
- jekyll-redirect-from